# Generated by Django 3.1.6 on 2021-05-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='model',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
